// Generated by GemminiExporter
#ifndef CONTEXT_TEST_DATA_H
#define CONTEXT_TEST_DATA_H

// Default types (can be overridden in main C file if needed)
#ifndef ELEM_T_DEFINED
typedef float elem_t;
typedef float acc_t;
#endif

#define SEQ_LEN 4
#define HIDDEN_DIM 4
#define NUM_HEADS 1
#define D_K 4
// Shape: (1, 1, 4, 4)
static elem_t probs_mat[1][1][4][4] = { 0.49495837, 0.3188888, 0.17737667, 0.008776145, 0.5761561, 0.08506496, 0.28002888, 0.058750123, 0.071496196, 0.788792, 0.102442436, 0.037269402, 0.13189332, 0.15609182, 0.12660041, 0.58541447 };

// Shape: (1, 1, 4, 4)
static elem_t v_mat[1][1][4][4] = { 1.6423169, -0.15959747, -0.49739754, 0.43958926, -0.75813115, 1.0783176, 0.80080056, 1.6806206, 1.2791244, 1.2964228, 0.6104665, 1.3347378, -0.23162432, 0.04175949, -0.2515753, 0.8598585 };

// Shape: (1, 1, 4, 4)
static elem_t expected_context[1][1][4][4] = { 0.795973, 0.49519098, 0.115249924, 0.9978071, 1.2263243, 0.36526322, -0.062290404, 0.8205158, -0.35818425, 0.97352284, 0.6492647, 1.5258693, 0.124614015, 0.335841, -0.0105955005, 0.992662 };

#endif