// Generated by GemminiExporter
#ifndef CPU_SOFTMAX_TEST_DATA_H
#define CPU_SOFTMAX_TEST_DATA_H

// Default types (can be overridden in main C file if needed)
#ifndef ELEM_T_DEFINED
typedef float elem_t;
typedef float acc_t;
#endif

#define SEQ_LEN 4
#define NUM_HEADS 1
#define SCALE_FACTOR 0.5f
// Shape: (1, 1, 4, 4)
static elem_t raw_scores[1][1][4][4] = { 19.269154, 14.872841, 9.007172, -21.05521, 6.7841845, -12.3454485, -0.4306748, -16.046669, -7.521353, 16.48723, -3.9247866, -14.036072, -7.2788134, -5.5943017, -7.688389, 7.624454 };

// Shape: (1, 1, 4, 4)
static elem_t expected_probs[1][1][4][4] = { 0.89532053, 0.099387415, 0.0052919714, 1.569113e-09, 0.9735179, 6.8296256e-05, 0.026403239, 1.0732164e-05, 6.117636e-06, 0.9999567, 3.694604e-05, 2.3546718e-07, 0.00057910214, 0.0013444421, 0.00047186392, 0.9976046 };

#endif