// Generated by GemminiExporter
#ifndef LN_TEST_DATA_H
#define LN_TEST_DATA_H

// Default types (can be overridden in main C file if needed)
#ifndef ELEM_T_DEFINED
typedef float elem_t;
typedef float acc_t;
#endif

#define SEQ_LEN 4
#define HIDDEN_DIM 4
// Shape: (1, 4, 4)
static acc_t input_acc_mat[1][4][4] = { 19.269154, 14.872841, 9.007172, -21.05521, 6.7841845, -12.3454485, -0.4306748, -16.046669, -7.521353, 16.48723, -3.9247866, -14.036072, -7.2788134, -5.5943017, -7.688389, 7.624454 };

// Shape: (1, 4, 4)
static elem_t expected_output_mat[1][4][4] = { 0.87157005, 0.5928135, 0.22088954, -1.685273, 1.3439873, -0.74730325, 0.5552442, -1.1519283, -0.4621773, 1.6423264, -0.14691558, -1.0332335, -0.6401417, -0.37352964, -0.7049663, 1.7186378 };

#endif