// Generated by GemminiExporter
#ifndef MATMUL_TEST_DATA_H
#define MATMUL_TEST_DATA_H

// Default types (can be overridden in main C file if needed)
#ifndef ELEM_T_DEFINED
typedef float elem_t;
typedef float acc_t;
#endif

// --- Dimensoes do Teste MatMul ---
#define SEQ_LEN 4
#define HIDDEN_DIM 4
// --- Entrada, Pesos, e Saida Esperada ---
// Shape: (1, 4, 4)
static elem_t input_mat[1][4][4] = { 0.3373702, -0.17777722, -0.3035276, -0.58801186, 0.3486052, 0.66034096, -0.21963762, -0.37916982, 0.76710707, -1.192502, 0.6983519, -1.4097229, 0.17937961, 1.895148, 0.49544638, 0.26919857 };

// Shape: (1, 4, 4)
static elem_t expected_output_mat[1][4][4] = { -0.37155744, -0.852951, 0.35785535, 0.98589957, -1.0502048, 0.3202539, -1.1130385, 0.59957576, -0.29256883, -0.050924003, 4.0784945, 1.8585896, -1.8230253, 2.4409025, -3.1917868, -1.095362 };

// Shape: (4, 4)
static elem_t Wq[4][4] = { -0.077020235, 1.5809696, 0.496471, -1.1588678, -1.0204719, 1.3010399, -1.5723042, 0.325471, -0.16895628, 1.2753012, 0.96657157, -0.63150537, 0.9177646, -0.2009531, -1.148144, -2.839994 };

// Shape: (4,)
static acc_t Wq_b[4] = { -0.038616218, -0.8861014, -0.47090015, -0.42690107 };

#endif