// Generated by GemminiExporter
#ifndef NORM_SOFTMAX_TEST_DATA_H
#define NORM_SOFTMAX_TEST_DATA_H

// Default types (can be overridden in main C file if needed)
#ifndef ELEM_T_DEFINED
typedef float elem_t;
typedef float acc_t;
#endif

#define SEQ_LEN 4
#define HIDDEN_DIM 4
// Shape: (1, 4, 4)
static acc_t input_acc_mat[1][4][4] = { 1.9269153, 1.4872841, 0.9007172, -2.105521, 0.67841846, -1.2345449, -0.043067478, -1.604667, -0.7521353, 1.648723, -0.39247864, -1.4036071, -0.7278813, -0.5594302, -0.7688389, 0.7624454 };

// Shape: (1, 4, 4)
static elem_t expected_output_mat[1][4][4] = { 0.49495837, 0.3188888, 0.17737667, 0.008776145, 0.5761561, 0.08506496, 0.28002888, 0.058750123, 0.071496196, 0.788792, 0.102442436, 0.037269402, 0.13189332, 0.15609182, 0.12660041, 0.58541447 };

#endif