// Generated by GemminiExporter
#ifndef QK_MATMUL_TEST_DATA_H
#define QK_MATMUL_TEST_DATA_H

// Default types (can be overridden in main C file if needed)
#ifndef ELEM_T_DEFINED
typedef float elem_t;
typedef float acc_t;
#endif

// --- Dimensoes do Teste QK_T MatMul ---
#define SEQ_LEN 4
#define HIDDEN_DIM 4
#define NUM_HEADS 1
#define HIDDEN_DIM_PER_HEAD 4
// --- Entrada (Q_buf, K_buf) ---
// Shape: (1, 4, 4)
static elem_t Q_buf[1][4][4] = { 1.5861957, 1.1253029, 1.8305902, 0.112888336, 0.49761096, 1.5009665, -0.14131775, -0.35217977, -0.16429015, -1.1650665, -0.40887636, -0.52516896, -1.3152609, 0.6031242, -0.81239426, 0.5919633 };

// Shape: (1, 4, 4)
static elem_t K_buf[1][4][4] = { -1.2265651, -0.95976996, 1.7117974, -0.0145567665, 0.42520776, -1.3445578, 1.6114134, 0.5913664, 0.16443714, 1.2514036, 0.517298, -0.807782, -2.07878, 0.63696945, 1.3823913, -0.9156325 };

// --- Saida Esperada (attn_scores_buf) ---
// Shape: (1, 4, 4)
static elem_t expected_attn_scores_buf[1][4][4] = { 0.10635185, 2.178024, 2.5248091, -0.15334028, -2.2877157, -2.2425368, 2.1715217, 0.048756838, 0.6274397, 0.5272057, -1.2722727, -0.4849541, -0.36487877, -2.3292303, -0.35995314, 1.4532422 };

#endif