// Generated by GemminiExporter
#ifndef RESADD_TEST_DATA_H
#define RESADD_TEST_DATA_H

// Default types (can be overridden in main C file if needed)
#ifndef ELEM_T_DEFINED
typedef float elem_t;
typedef float acc_t;
#endif

#define SEQ_LEN 4
#define HIDDEN_DIM 4
// Shape: (1, 4, 4)
static elem_t input_A[1][4][4] = { 1.8616195, 0.9035294, 1.339468, 1.2004706, 1.0069944, 0.23791505, -0.4196906, 0.5357962, -0.3830784, 2.1766753, 0.9645259, 0.48470715, -1.7430543, -1.1125325, -0.057416346, -1.6394427 };

// Shape: (1, 4, 4)
static elem_t input_B[1][4][4] = { -0.87204725, -0.14759809, -0.23570831, 0.5441309, -0.5091446, -0.980791, 1.285977, 0.8199674, 1.3823497, 0.85287184, 0.97097975, 0.67441416, -0.32127005, 1.7001469, 0.31254455, -0.9294907 };

// Shape: (1, 4, 4)
static elem_t expected_sum[1][4][4] = { 0.9895722, 0.7559313, 1.1037596, 1.7446015, 0.49784976, -0.74287593, 0.8662864, 1.3557637, 0.99927133, 3.0295472, 1.9355056, 1.1591213, -2.0643244, 0.5876144, 0.2551282, -2.5689335 };

#endif