// Generated by GemminiExporter
#ifndef SOFTMAX_TEST_DATA_H
#define SOFTMAX_TEST_DATA_H

// Default types (can be overridden in main C file if needed)
#ifndef ELEM_T_DEFINED
typedef float elem_t;
typedef float acc_t;
#endif

#define SEQ_LEN 4
#define BERT_SCALE_VAL 0.5f
// Shape: (1, 1, 4)
static elem_t input_scores_mat[1][1][4] = { 0.33669037, 0.1288094, 0.23446237, 0.23033303 };

// Shape: (4, 4)
static elem_t identity_mat[4][4] = { 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 };

// Shape: (1, 1, 4)
static elem_t expected_probs_mat[1][1][4] = { 0.26318145, 0.2371999, 0.2500672, 0.24955145 };

#endif