#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#ifndef BAREMETAL
#include <sys/mman.h>
#endif

// --- 1. Define Types for Quantization ---
// This tells the Gemmini headers to use int8 for storage
// and int32 for accumulation (to avoid overflow during matmul)
// #define ELEM_T_DEFINED
// typedef int8_t elem_t;
// typedef int32_t acc_t; 

#include "include/gemmini.h"
#include "include/gemmini_nn.h"

// Include the params generated by the new Python script
#include "includes/simple_mlp_params.h"

// Helper to convert back to float for printing/debugging
float dequantize(elem_t x, float scale) {
    return (float)x * scale;
}

int find_max_index(elem_t* arr, int size) {
    int max_idx = 0;
    elem_t max_val = arr[0];
    for (int i = 1; i < size; i++) {
        if (arr[i] > max_val) {
            max_val = arr[i];
            max_idx = i;
        }
    }
    return max_idx;
}

int main (int argc, char * argv[]) {
#ifndef BAREMETAL
    if (mlockall(MCL_CURRENT | MCL_FUTURE) != 0) {
      perror("mlockall failed");
      return 1;
    }
#endif

    gemmini_flush(0);

    // Buffers for intermediate results (now int8_t via elem_t)
    static elem_t inter_results0[BATCH_SIZE][HIDDEN1_SIZE];
    static elem_t inter_results1[BATCH_SIZE][HIDDEN2_SIZE];
    static elem_t output_results[BATCH_SIZE][OUTPUT_SIZE];

    uint64_t start, end;

    printf("--- Starting INT8 SimpleMLP Inference --- \n");

    /* Layer 0 */
    start = read_cycles();
    // Pass LAYER0_SCALE. Gemmini accumulates in int32, then multiplies by this float
    // to shrink the result back down to int8 range.
    tiled_matmul_nn_auto(BATCH_SIZE, HIDDEN1_SIZE, INPUT_SIZE,
        input_mat, weights0, NULL, inter_results0,
        RELU, LAYER0_SCALE, false, 
        WS, false, "layer_0_fc1");
    end = read_cycles();
    printf("Layer 0 Cycles: %llu\n", end-start);

    /* Layer 1 */
    start = read_cycles();
    tiled_matmul_nn_auto(BATCH_SIZE, HIDDEN2_SIZE, HIDDEN1_SIZE,
        inter_results0, weights1, NULL, inter_results1,
        RELU, LAYER1_SCALE, false,
        WS, false, "layer_1_fc2");
    end = read_cycles();
    printf("Layer 1 Cycles: %llu\n", end-start);

    /* Layer 2 */
    start = read_cycles();
    // Final layer usually has no activation or scaling if it's just logits (ArgMax works anyway),
    // BUT to keep numbers in int8 range, we still apply the scale.
    tiled_matmul_nn_auto(BATCH_SIZE, OUTPUT_SIZE, HIDDEN2_SIZE,
        inter_results1, weights2, NULL, output_results,
        NO_ACTIVATION, LAYER2_SCALE, false,
        WS, false, "layer_2_fc3");
    end = read_cycles();
    printf("Layer 2 Cycles: %llu\n", end-start);

    // --- Verification ---
    int prediction = find_max_index((elem_t*)output_results, OUTPUT_SIZE);
    printf("Prediction index: %d\n", prediction);

    // Optional: Print some dequantized values to see if they look like reasonable logits
    /*
    printf("First few outputs (approx floats):\n");
    for(int i=0; i<5 && i<OUTPUT_SIZE; i++) {
        // Note: We don't have the exact output_scale here easily unless we saved it in Python
        // But raw int8 values are enough for ArgMax
        printf("%d ", output_results[0][i]); 
    }
    printf("\n");
    */

    return 0;
}