#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>

#include "include/gemmini.h"
#include "include/gemmini_nn.h"

// Include the header generated by the Python script
#include "includes/quantized_matmul_params.h"

int main() {
    gemmini_flush(0);
    printf("=== Gemmini Quantized MatMul Test (Bit-Exact) ===\n");
    printf("Dims: %d x %d\n", MAT_M, MAT_N);
    printf("Scale: %f\n", REAL_SCALE);

    static elem_t C_result[MAT_M][MAT_N] row_align(1);

    // 1. Run Hardware MatMul
    uint64_t start = read_cycles();

    tiled_matmul_auto(
        MAT_M, MAT_N, MAT_K,
        (elem_t*)mat_A,       
        (elem_t*)mat_B,       
        (acc_t*)bias,         
        (elem_t*)C_result,    
        
        MAT_K, MAT_N, MAT_N, MAT_N, // Strides
        
        MVIN_SCALE_IDENTITY, MVIN_SCALE_IDENTITY, MVIN_SCALE_IDENTITY,
        NO_ACTIVATION,
        
        // Pass the float scale
        // Hardware converts: 0.03125 -> Multiplier 1, Shift 5
        (acc_scale_t)REAL_SCALE, 
        
        0, 
        true, // repeating_bias = true (Broadcasts 1xN bias)
        false, false,
        false, false,
        0,
        WS
    );

    gemmini_fence();
    uint64_t end = read_cycles();

    // 2. Verify Results
    int errors = 0;
    
    printf("Result [0][0]: Got %d (Expected %d)\n", C_result[0][0], expected_C[0][0]);

    for (int i = 0; i < MAT_M; i++) {
        for (int j = 0; j < MAT_N; j++) {
            elem_t produced = C_result[i][j];
            elem_t expected = expected_C[i][j];

            if (produced != expected) {
                if (errors < 5) { 
                     printf("  [FAIL] @ [%d][%d]: Exp %d, Got %d (Diff: %d)\n", 
                            i, j, expected, produced, produced - expected);
                }
                errors++;
            }
        }
    }

    if (errors == 0) {
        printf("SUCCESS: Output matches Golden reference!\n");
        return 0;
    } else {
        printf("FAILURE: Found %d errors.\n", errors);
        return 1;
    }
}